##########################################################
## App name settings                                    ##
## org.springframework.boot:spring-boot                 ##
## -> spring-boot-XXX.jar                               ##
## -> org.springframework.boot -> context               ##
## -> ContextIdApplicationContextInitializer.class      ##
##########################################################
spring.application.name=Midterm

##########################################################
## Database settings                                    ##
## org.springframework.boot:spring-boot-jdbc            ##
## -> spring-boot-jdbc-XXX.jar                          ##
## -> org.springframework.boot.jdbc -> autoconfigure    ##
## -> DataSourceProperties.class                        ##
##########################################################
spring.datasource.driverClassName=com.mysql.cj.jdbc.Driver
spring.datasource.url=jdbc:mysql://localhost:3306/SpringEcommerce?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=root

##############################################################
## SQL settings                                             ##
## org.springframework.boot:spring-boot-hibernate           ##
## -> spring-boot-hibernate-XXX.jar                         ##
## -> org.springframework.boot.hibernate -> autoconfigure   ##
## -> HibernateProperties.class                             ##
##                                                          ##
## org.springframework.boot:spring-boot-jpa                 ##
## -> spring-boot-jpa-XXX.jar                               ##
## -> org.springframework.boot.jpa -> autoconfigure         ##
## -> JpaProperties.class                                   ##
##                                                          ##
## org.hibernate.core:hibernate-core                        ##
## -> hibernate-core-XXX.jar                                ##
## -> org.hibernate -> cfg                                  ##
## -> JdbcSettings.class                                    ##
##############################################################
spring.jpa.hibernate.ddlAuto=create
spring.jpa.showSql=true

##############################################################
## Jwt properties                                           ##
##############################################################
jwt.secret=THIS_IS_A_SECRET_MESSAGE_YOU_CANNOT_FORGET
# 7 days = 7 (days) * 24 (hours) * 60 (minutes) * 60 (seconds) * 1000 (miliseconds)
jwt.expiration=604800000

##############################################################
## Logging settings                                         ##
## org.springframework.boot:spring-boot                     ##
## -> spring-boot-XXX.jar                                   ##
## -> org.springframework.boot -> context -> logging        ##
## -> LoggingApplicationListener.class                      ##
##                                                          ##
## org.springframework.boot:spring-boot                     ##
## -> spring-boot-XXX.jar                                   ##
## -> org.springframework.boot -> logging                   ##
## -> LogLevel.class                                        ##
##                                                          ##
## logging.level.[package or class]=[LogLevel]              ##
##############################################################
logging.level.org.springframework.web=DEBUG